### ISSUE TITLE
Make it possible to look through the whole history

### ISSUE THREAD

**Issue by link2xt** [webratte/Shared-Memo#25]
Currently if there are 3 updates, it is only possible to see the current and the previous version.
It would be nice to be able to review all the versions, especially in case of parallel edits by multiple users (#14).

**Comment by webratte** [comment]
Thank you for your suggestion.

I'm not sure will this be a good idea.
I have always send the whole history around.

Anyway. My skills ar not enough for this at the moment 😉

**Comment by link2xt** [comment]
There is no need to resend the whole history, you can always look at previous updates.

**Comment by webratte** [comment]
Step by step I investigate how it works. Hopefully someday I will understand 😉

**Comment by webratte** [comment]
I think 10 steps backwards is enough. So the start will always be fast.
Maybe in a future version I will make it to a user preference. This way, people with fast devices can set a larger number of history. People with slower devices can set a lower number.

**Comment by webratte** [comment]
Closed via https://github.com/webratte/Shared-Memo/commit/678e18a69e1f6ef4e4932026de6ee66157f5a198
