### ISSUE TITLE
add "webxdc" topic

### ISSUE THREAD

**Issue by r10s** [webratte/Shared-Memo#4]
that way, it will be discoverable using https://github.com/topics/webxdc (which is linked eg. from the [help](https://docs.webxdc.org/get_started.html)).

you find the corresponding options in the upper right corder of your repo:

<img width=480 src=https://user-images.githubusercontent.com/9800740/192864818-3227d83e-66fe-4a8a-bdd6-52213cf415b3.png>

we can maybe also transfer ownership to <https://github.com/webxdc>, however, i am not totally sure how to do this :)

however adding a topic is be a first step needed anyway.

**Comment by webratte** [comment]
Done.
