### ISSUE TITLE
transfer this repo to github.com/webxdc ?

### ISSUE THREAD

**Issue by r10s** [webratte/Shared-Memo#5]
i am not totally sure how this can be done easiest.

an "outside collaborator" might be the thing to go for, you would have full access on a repo inside github.com/webxdc - without having the risk to break things otherwise. we are using this grant already eg. for https://github.com/webxdc/the-cube.xdc 

maybe you can add me as an owner to _this_ repository and i can transfer it then and add you as a collaborator to  github.com/webxdc ?

if you do not want this, feel free to close this issue.

**Comment by webratte** [comment]
I have to think about it.
Of course I trust you.
But I'm currently in a playing phase yet.
So it's possible I do some mischief 😉

Probably it's better to wait until I will know more about Github. 

I think will come back later. 

And thank you for your help.

**Comment by webratte** [comment]
I will keep this open as memo for myself until I will come back.

**Comment by webratte** [comment]
I still playing around. However, I still sent you a invitation to my Repo.
If I do something wrong, please let me know.

**Comment by webratte** [comment]
I think I was wrong. Sorry. But now I have to go to work. 
I will come back later.

**Comment by webratte** [comment]
There will come a store-solution for sharing privat Apps. 
So porting is not needed anymore.

Thank you anyway.

**Comment by r10s** [comment]
yeah, looking forward to see "Shared-Memo" in the store!
